### ISSUE TITLE
mingw-w64 is now available in v11.0.0, please update it

### ISSUE THREAD

**Issue by typarcx** [mmozeiko/build-gcc-mingw#2]

**Comment by mmozeiko** [comment]
I've updated to v11.

**Comment by typarcx** [comment]
Thank you very much for the update!













Crush
***@***.***


---Original---
From: "Mārtiņš ***@***.***&gt;
Date: Sun, Jul 9, 2023 23:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mmozeiko/build-gcc-mingw] mingw-w64 is now available in v11.0.0,please update it (Issue #2)




 
I've updated to v11.
