### ISSUE TITLE
使用GCC14的PRINT函数出现错误

### ISSUE THREAD

**Issue by YH2021-cc** [mmozeiko/build-gcc-mingw#4]
只包括头文件不适用print/println函数没问题，一使用就报错

> 报错代码

![image](https://github.com/mmozeiko/build-gcc-mingw/assets/84270940/d977345e-f903-4fe8-9920-024b82b9f177)

> 测试代码

![image](https://github.com/mmozeiko/build-gcc-mingw/assets/84270940/5db13e18-0e95-405e-9b7e-0dd71cb11355)

> cmake文件

![image](https://github.com/mmozeiko/build-gcc-mingw/assets/84270940/19933b54-27ef-48a8-897f-7a60bb90a002)

> 不使用print函数

![image](https://github.com/mmozeiko/build-gcc-mingw/assets/84270940/f8d90de6-8228-4968-8f28-569faeb64dff)

> gcc版本

![image](https://github.com/mmozeiko/build-gcc-mingw/assets/84270940/12ca3b55-260a-4296-91ff-999296b0abba)

**Comment by mmozeiko** [comment]
std::print support on Windows requires linking to experimental libstdc++ runtime library.

See https://gcc.gnu.org/gcc-14/changes.html
> std::print and std::println (requires linking with -lstdc++exp on Windows).

**Comment by YH2021-cc** [comment]
谢谢
